### ISSUE TITLE
/save API endpoint is broken

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#224]
Save endpoint doesn't do what it's supposed to.

Let's fix that :)

* [x] close qri-io/cafs#9
* [ ]  close qri-io/dataset#64
* [ ]  close qri-io/dataset#63
* [x] create SaveReqParams that allows you to encode/decode the request body
* [x] check necessary input given (name, savetitle, and DataFilename, StructureFilename, or MetaFilename required)
using cmd/save.go as a modal:
* [x] declare a new core.SaveParams and add populate with user input from SaveReqParams (add Name, SaveTitle, & SaveMessage) (load Data, Structure, and Meta files from path inputs)
* [x] call save on the datasethandler with the core.SaveParam{} and new repo.DatasetRef
* [x] make sure tests pass
