### ISSUE TITLE
add API endpoint can't handle adding structure or meta data

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#229]
* [x] close #248
* [x] if is p.Metadata is empty, and p.MetadataFilename is not empty, open file and add to InitParams
* [x] if is p.Structure is empty, and p.StructureFilename is not empty, open file, and add to InitParams
* [x] in the default of the switch: following the pattern to open a data file from form, rather than json, add metadata and structure
