### ISSUE TITLE
refactor: remove `ProfileID` from datasetRef.String()

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#976]
## Summary

Dataset references are how we refer to a specific dataset version. A typical dataset reference, when printed for the user, contains a **Peername**, a dataset **Name**, and a hashed **Path** that references a specific version:
`ramfox/my_dataset@/ipfs/QmPath`

However, a dataset reference can also contain a **ProfileID**, which is the immutable ID associated with a peer (aka a user). 
`ramfox/my_dataset@QmProfileID/ipfs/QmPath`

A `ProfileID` and a version `Path` are in the same format: a hashed string of 46 characters beginning with `Qm`. This can cause confusion when a user is reading a dataset reference. 

To add to the confusion, these `ProfileID`s are *sometimes* showing up in our output and *sometimes* not (depending on if a dataset reference object contains the `ProfileID` at the point). Let's remove the confusion and avoid situations where a user will have to come into contact with a *hash* that may or may not be a `ProfileID` or a `Path`

(For a more in depth discussion of naming, check out our [docs on the subject](https://qri.io/docs/concepts/names/))

As per discord convo with @Mr0grog, there are a ton of hashes flying around on the CLI (command line interface). Because a user never really needs to know their own `ProfileID` (since `ProfileID`s are how qri resolves names internally, not how a user recognizes themselves), we should remove references to `ProfileID` in any CLI or API responses, when those responses print the dataset reference.

### discussion
We discussed two options:

1) we refactor the `repo` package, to have the `datasetRef.String()` function return the `peername/dataset_name@/network/hash`. And create a `datasetRef.Absolute()` to return `peername/dataset_name@profileID/network/hash`

OR

2) We add a `datasetRef.Pretty()` which returns `peername/dataset_name@profileID/network/hash`, and we add `ref.Pretty()` to any places in CLI or API responses that attempt to stringify a datasetRef 

### Get down to work:
As per the below convo, we decided to go with option 1:
- refactor `datasetRef.String()` to remove the ProfileID
- create a `datasetRef.Absolute()` that will have the behavior of `datasetRef.String()` before the refactor

`datasetRef.String()` is defined in qri/repo/ref.go:
https://github.com/qri-io/qri/blob/1fe4086ced2093bc6b56daa4d2f1b730cde658fd/repo/ref.go#L109-L121

The  new `datasetRef.Absolute()` function should be defined near the `datasetRef.String()` function.

### Todo:
This issue can be closed when all these todos have been finished:

* [ ] Refactor `ProfileID` out of the `datasetRef.String()` function.
* [ ] Add a `datasetRef.Absolute()` function with the signature:
```go
func (r DatasetRef) Absolute() string
```
* [ ] adjust `cases` struct in the `qri/repo/refs_test.go` file:
    * [ ] add an `Absolute    string` field that tests the output of `Absolute()`
    * [ ] remove the `ProfileID`s from the `cases.String` field
* [ ] add a `TestDatasetRefAbsolute(t *testing.T)` function that iterates through `cases` and tests that the output of `Absolute()` is returning as expected 
* [ ] There should be a few tests in other packages that expect the `ProfileID` in the output. See what fails and update those tests accordingly.

**make sure to read through the `DEVELOPERS.md` doc, specifically the [commit guidelines](https://github.com/qri-io/qri/blob/master/DEVELOPERS.md#commits), when pushing commits & reach out at our [discord](https://discord.gg/etap8Gb) for any questions :)**

**Comment by b5** [comment]
totally agreed with removing the display of profileID's. I like option 1.

The `.String()` method should always reflect the _default_ display, and I think the default display should be whatever is easiest for the reader. We could consider adding an `.Absolute()` method that includes the profileID string. That'll be very necessary when we start doing key rotation.

**Comment by nikon72ru** [comment]
hi!
It's my very first time to contribute in open source, but i have about 2 years experience in Go programming. I think i can do it. 
I not sure if need to notify you before i start or just do things and create pull request :smile:

**Comment by b5** [comment]
@nikon72ru welcome! Sounds great! Feel free to start, and open a [draft pull request](https://github.blog/2019-02-14-introducing-draft-pull-requests/) once you have your first commit. We can work with you as you go!

Welcome to the world of open source 😄

**Comment by ramfox** [comment]
Wooooo @nikon72ru welcome!!!! Post any questions to the draft pr or this issue and we are happy to help!
